language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION=0.12
  - NODE_VERSION=4 CC=clang CXX=clang++
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - nvm install $NODE_VERSION
before_script:
  - npm install
script:
  - npm test
