language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION="0.11"
  - NODE_VERSION="0.10"
before_install:
  - nvm install $NODE_VERSION
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - npm install
script:
  - npm test
